const Products = [
    {
      id: 1,
      name: "Wireless Bluetooth Headphones",
      description: "High-quality over-ear headphones with noise cancellation and up to 20 hours of battery life.",
      price: 2999,
      category: "Electronics",
      stock: 50,
      image: "https://m.media-amazon.com/images/I/41JACWT-wWL._AC_SY400_.jpg",
      rating: 4.5,
    },
    {
      id: 2,
      name: "Running Shoes",
      description: "Lightweight running shoes with excellent grip and durability, perfect for all terrains.",
      price: 1999,
      category: "Footwear",
      stock: 100,
      image: "https://m.media-amazon.com/images/I/71WXVepOnFL._AC_SY400_.jpg",
      rating: 4.3,
    },
    {
      id: 3,
      name: "Smartphone",
      description: "Latest model smartphone with a 6.5-inch display, 128GB storage, and a powerful processor.",
      price: 21999,
      category: "Electronics",
      stock: 30,
      image: "https://m.media-amazon.com/images/I/715WPVOynNL._AC_SY400_.jpg",
      rating: 4.8,
    },
    {
      id: 4,
      name: "Stainless Steel Water Bottle",
      description: "Eco-friendly, insulated water bottle that keeps beverages hot or cold for hours.",
      price: 699,
      category: "Home & Kitchen",
      stock: 200,
      image: "https://m.media-amazon.com/images/I/61fg6FjVTIL._AC_SY400_.jpg",
      rating: 4.7,
    },
    {
      id: 5,
      name: "Gaming Mouse",
      description: "Ergonomic gaming mouse with customizable RGB lighting and programmable buttons.",
      price: 1499,
      category: "Accessories",
      stock: 75,
      image: "https://m.media-amazon.com/images/I/61+R5rOj9+L._AC_SY400_.jpg",
      rating: 4.6,
    },
    {
        id: 6,
        name: "Gaming Mouse",
        description: "Ergonomic gaming mouse with customizable RGB lighting and programmable buttons.",
        price: 1699,
        category: "Accessories",
        stock: 75,
        image: "https://m.media-amazon.com/images/I/515GyXy58wL._AC_SY400_.jpg",
        rating: 4.8,
      },
  ];
  
  export default Products;
  